// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByf-iPmx1lKmG6gx9NzJBASBzrUDLeEDo',
    appId: '1:29791646039:web:ce4608bb8ec02c45cb0e12',
    messagingSenderId: '29791646039',
    projectId: 'anyone-f99a5',
    authDomain: 'anyone-f99a5.firebaseapp.com',
    storageBucket: 'anyone-f99a5.appspot.com',
    measurementId: 'G-T4B4EH66FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdHcXosg19NmxUJlmgPN5NieJpM8qR5uY',
    appId: '1:29791646039:android:c0c120bf5d862939cb0e12',
    messagingSenderId: '29791646039',
    projectId: 'anyone-f99a5',
    storageBucket: 'anyone-f99a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJG48xVOF-nKG83Di3YGYPUQnh6hqxweE',
    appId: '1:29791646039:ios:bbe9630ad3719179cb0e12',
    messagingSenderId: '29791646039',
    projectId: 'anyone-f99a5',
    storageBucket: 'anyone-f99a5.appspot.com',
    iosClientId: '29791646039-r6aq56117kdrrdldu0a13ledtbf1posc.apps.googleusercontent.com',
    iosBundleId: 'com.leecha.anyone',
  );
}
